### ISSUE TITLE
Problem with time management

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#1]
There is a potential issue in the increment loop management. In fact, the TimeStep features current time, time increment and increment number, which is passed to the applications via the API for the solution of the increment. However, the time control in the mupif workflow also uses the simulation end time, called targetTime in the examples, to control the increment loop. This targetTime is not communicated to the application via the API, but may be required by the application, for example for scaling the boundary conditions (non-zero displacements, pressures, nodal loads) in the increment loop, i.e. load=max_load*time/targetTime. The way it works now is that the target time is defined independently in both the workflow and in the input file of the application (if there is any), This may be a source of error if those targetTimes are not set identical values. It might be usefull to include a method in  the API for getting/setting targetTime, or includeing it into the TimeStep class.

**Comment by bpatzak** [comment]
Thank you for pointing this out. I fully agree with you. 
We will extend the TimeStep class with an additional targetTime attribute.

**Comment by bpatzak** [comment]
We have introduced targetTime attribute in the 2.0 MuPIF version. This should solve the problem.
