### ISSUE TITLE
New problem with getFieldURI

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#14]
Using mupif-2.0.6, I get the following erro message, using openvpn or ssh, windows or linux:

Traceback (most recent call last):
  File "testrundist-v1.py", line 136, in <module>
    uri = app1.getFieldURI(FieldID.FID_Displacement,istep.getTime().inUnitsOf('s').getValue())
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 179, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/Pyro4/core.py", line 451, in _pyroInvoke
    raise data
mupif.APIError.APIError: Error: can not obtain field

Any idea where this comes from?

**Comment by vit-smilauer** [comment]
Dear Gaston,
it seems to be related with getField() extension with objectID=0, which is now
def getField(self, fieldID, time, **objectID=0**)

In your application, you need to extend your function getField() with **objectID=0** so it correctly redefines abstract function in Application.py. Sorry for this change, it was necessary to separate Fields to different inclusions with their objectIDs, following the same concept as in getProperty(self, propID, time, objectID=0).

Vit

**Comment by grauchs** [comment]
Dear Vit,
The problem is now solved!
