### ISSUE TITLE
How do I get remote jobManWorkDir

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#15]
In the workflow control script, I can upload the input file for the application to the application server using getPyroFile and PyroUtil.uploadPyroFile. However, in the model.initialize method, I have to give the working directory where the file is located. How do I get the working directory of a remote application server?

**Comment by eudoxos** [comment]
Hi, I am closing old issues which (unfortunately) are stale and without response. I believe these issues are solved in newer versions of MuPIF. There were substantial refactoring in how we handle `PyroFile` (see [PyroFile_TestCase](https://github.com/mupif/mupif/blob/master/mupif/tests/test_pyro.py#L15)); location of the remote file is unneeded to operate on the file and hidden by the API.
