### ISSUE TITLE
data accessibility in workflow method

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#17]
In the workflow class in Workflow.py, the solve method contains a self.terminate() command at the end. This means that after executing the solve method in a workflow, access to fields or properties are no more possible. So it may be useful to remove the command from the solve method. One could call the terminate method in the same workflow than the one that initializes the workflow, for example.

**Comment by eudoxos** [comment]
Hi, I am closing old issues which (unfortunately) are stale and without response; sorry. I am not sure about the response myself, please reopen if this issue still concerns you and we can look at it.
