### ISSUE TITLE
Issue with fields read by makeFromVTK3

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#19]
With makeFromVTK3, I manage to read a field from a vtk file. I also can access the field information using different field methods. However, when I try to evaluate the field, I get the following error message:
Traceback (most recent call last):
  File "meshinput.py", line 190, in <module>
    print ('point value ', i+1,vtkfield[0].evaluate(transform(point, M),eps=.000001).getValue())
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Field.py", line 223, in evaluate
    return PhysicalQuantity(self._evaluate(positions, eps), self.unit)
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Field.py", line 236, in _evaluate
    cells = self.mesh.giveCellLocalizer().giveItemsInBBox(BBox.BBox([c-eps for c in position], [c+eps for c in position]))
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Mesh.py", line 523, in giveCellLocalizer
    bb = ccc.__iter__().__next__().getBBox()  # use the first bbox as base
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Cell.py", line 161, in getBBox
    c = self.mesh.getVertex(vertex).coords
  File "C:\Users\rauchs\AppData\Roaming\Python\Python37\site-packages\mupif\Mesh.py", line 469, in getVertex
    return self.vertexList[i]
TypeError: list indices must be integers or slices, not Vertex

**Comment by bpatzak** [comment]
Can you send us the vtk file and sample code?  That would enable to seek for the error.

**Comment by grauchs** [comment]
Dear Borek,

Here it is.

In fact, the, I got the vtk file from the Composelector Github.
Best reg(See attached file: FibreOrientation_test-v1.vtk)(See attached
file: meshinput.py)(See attached file: testpanel-v1.inp)ards, Gast
-----------------------------------------------------------------------------------

Dr.-Ing. Gast Rauchs
Materials Research and Technology Department
Luxembourg Institute of Science and Technology
5, rue Bommel
Z.A.E. Robert Steichen
L-4940 Uewerkäerjeng
Tel.: +352 275 888 4508 Fax : +352 275 885
--------------------------------------------------------------------------------------

Email: gaston.rauchs@list.lu

**Comment by bpatzak** [comment]
Dear Gaston.
I believe I have fixed the problem. Please pull the changes from repository or download Mesh.py file manually. Note, I am out of office now, so I did not checked if the field evaluation gives the correct results, but your example now run without errors. Once back, I will check.
