### ISSUE TITLE
Problem with definition of dimensionless units

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#21]
Here is a description of the problem:
When properties get transferred between digimat and abaqus in the solvestep() method, everything goes fine. In workflow runs without digimat, I define the composite properties in the workflow() method. Here for the Poissons ratio, which is dimensionless, the solver.setProperty() method in the solvestep() method exited with an error about a division by zero! I was able to track the error down to the inUnitsof() method.
I checked that in workflow runs with and without digimat intervention, screen output of the defined properties was exactly the same! Now, when in the workflow() method, I changed the setProperty from

workflow.setProperty(Property.ConstantProperty(compositeInPlanePoisson, PropertyID.PID_CompositeInPlanePoisson, ValueType.Scalar, PQ.getDimensionlessUnit(), None, 0))
workflow.setProperty(Property.ConstantProperty(compositeTransversePoisson, PropertyID.PID_CompositeTransversePoisson, ValueType.Scalar, PQ.getDimensionlessUnit(), None, 0))

to

workflow.setProperty(Property.ConstantProperty(compositeInPlanePoisson, PropertyID.PID_CompositeInPlanePoisson, ValueType.Scalar, 'none', None, 0))
workflow.setProperty(Property.ConstantProperty(compositeTransversePoisson, PropertyID.PID_CompositeTransversePoisson, ValueType.Scalar, 'none', None, 0))

everything went fine. This means replacing PQ.getDimensionlessUnit() by 'none' fixes the problem. So it looks like in some cases PQ.getDimensionlessUnit() is not treated the same way as 'none'. despite the unit of the property being output as none in both cases. In addition to that, this problem with dimensionless properties did not intervene with properties of other solvers like digimat or lammps. So where could the error be?

**Comment by eudoxos** [comment]
Hi, I am closing old issues which (unfortunately) are stale and without response. I believe these issues are solved in newer versions of MuPIF. This particular won't appear as we migrated to astropy-based unit objects and the `dimensionless_unscaled` unit is accessed as `astropy.units.Unit('none')` or (as shorthand) `mupif.U.none`.
