### ISSUE TITLE
Problem with Field.evaluate method

### ISSUE THREAD

**Issue by grauchs** [mupif/mupif#3]
When I call the evaluate function in the setField method, I get the following error message:
Traceback (most recent call last):
  File "testrun-v4.py", line 71, in <module>
    app2.setField(res1)
  File "/home/rauchs/ComPoSTe/Interface/composteAPI.py", line 296, in setField
    vec=field.evaluate(node.getCoordinates(),0.5)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 196, in evaluate
    return self._evaluate(positions, eps)
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 219, in _evaluate
    answer = icell.interpolate(position, [self.values[i.number] for i in icell.getVertices()])
  File "/usr/local/lib/python3.6/site-packages/mupif-1.1.6-py3.6.egg/mupif/Field.py", line 219, in <listcomp>
    answer = icell.interpolate(position, [self.values[i.number] for i in icell.getVertices()])
AttributeError: 'numpy.int64' object has no attribute 'number'

The field should be correctly defined (I manage to view it in Paraview by vtk output), the evaluation point is inside a cell, for debugging I can output the vertices, cell vertices, values etc. in the setField method before calling evaluate().
I am even able to output the field values using either field.values[inode.getNumber()] or field.values[inode.number], the latter appearing in the error message

**Comment by vit-smilauer** [comment]
Hi,
I think this relates to number type. Previously, we assumed that Cell.vertices have type int. However, having numpy.int64 screwed up Cell.getVertices(). Now, it was extended to all integers, including numpy.int64.
If it does not work, send me your testrun-v4.py to have a closer look.

Regards. Vit

**Comment by grauchs** [comment]
It works!

**Comment by vit-smilauer** [comment]
Seems to be fixed, changed tensor representation to a tuple with 9 components. Example10*/TensorFieldTest.py checks interpolation.
