### ISSUE TITLE
mupif.Mesh.UnstructuredMesh is not imported

### ISSUE THREAD

**Issue by bpatzak** [mupif/mupif#30]
In dev branch, when importing mupif one could not create instance of mupif.Mesh.UnstructuredMesh
Example:
import mupif
instance = mupif.Mesh.UnstructuredMesh()

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Mesh' has no attribute 'UnstructuredMesh'

**Comment by eudoxos** [comment]
`mupif.Mesh` is an alias for `mupif.mesh.Mesh` (modules in lowercase), one of the following will work (please confirm):
```python
import mupif
instance1=mupif.mesh.UnstructuredMesh() # exposes internal source structure
instance2=mupif.UnstructuredMesh() # this is intended for end-users
```

**Comment by bpatzak** [comment]
thank you, it works. I am confused by this as switching between master and dev branch two times today.
