### ISSUE TITLE
example11 simplifications

### ISSUE THREAD

**Issue by eudoxos** [mupif/mupif#31]
Hi Borek,

is this loop only supposed to copy data over? In that case, we might just have a method which will copy the underlying HDF5 file (as file, e.g. `shutil.copy`) and open a new handle using the copy; would that be a good solution?

https://github.com/mupif/mupif/blob/efb2ea65be0ff8a813be97277b6fe2fdf06c0cb0/examples/Example11/model2.py#L84-L98

To replace the molecule, there is a few functionality in the last commit, so it could be done via the `inject` (perhaps `replace` would be a better name for that?) method:

https://github.com/mupif/mupif/blob/efb2ea65be0ff8a813be97277b6fe2fdf06c0cb0/examples/Example11/model2.py#L109-L123

could be replaced with something like

```python
outGrains[rgNum].getMolecules()[rmNum].inject(inGrains[1].getMolecules()[3])
```
The inject method internally invokes `to_dump` and then `from_dump`, so all the data must fit into RAM; `from_dump` handles all resizing as necessary, and also converts units (if they happen to differ). The test uses `to_dump` and `from_dump` but I don't think those need to be exposed to the API, as we would be opening our storage structure to the users:

https://github.com/mupif/mupif/blob/e75828abdf141d02d2668c0df8f8138c4a047429/mupif/tests/test_heavydata.py#L109-L146

I don't want to touch example11 without coordination, so please modify it according to your consideration or we can talk so that I can do it.

**Comment by eudoxos** [comment]
I added the simplified options as default branches to the code; feel free to delete the low-level variants if you don't see them as necessary to keep https://github.com/mupif/mupif/blob/b69bdf2135b9e5b4e041f4b4b6f4fe1193e674c0/examples/Example11/model2.py#L75-L152

**Comment by bpatzak** [comment]
Hi, I think the first option (copy old state into a new one) should be avoided, as the use needs knowledge about internal representation (needs to copy file). The code at this level should abstract from this and rely solely on methods provided by a datatype. 
The second option is ok. But what is the difference between inject and set method?

**Comment by eudoxos** [comment]
> Hi, I think the first option (copy old state into a new one) should be avoided, as the use needs knowledge about internal representation (needs to copy file).

The file copy could be hidden by a method or perhaps by an additional data access mode, e.g. `getData(mode='clone',...)`. It is by far the most efficient way of cloning the data.

> But what is the difference between inject and set method?

`inject` takes another context as parameter (the data pass through serialization/deserizalization in RAM) and replaces the whole subtree. `set*` methods are only defined for leaf nodes (such as `setMolecularWeight(…)`) , not for a whole hierarchy of data (there is no `setMolecules(…)`, for instance).

**Comment by bpatzak** [comment]
If abstracted by  method (like copy()) then the first approach is ok. My objections were mainly to the direct file copying in workflow.
Related to the second, from a perspective of the user, who has no knowledge about the internals, the meaning of _inject_ and _set_ methods is quite close. Can we merge them together? So there will be jut _set_ method defined for leaf nodes as well as for sub trees.
