### ISSUE TITLE
Octree localizer takes 10 minutes to fill for 155k-tetra mesh

### ISSUE THREAD

**Issue by eudoxos** [mupif/mupif#74]
I was testing HeavyMesh with 155k tetra elements (175k vertices). The localizer takes 599s to build in RAM (subsequent field evaluations are fast). @bpatzak, is that acceptable or do we need to look at something more efficient?

(The octree infinite subdivision bug #73 was not a bug in octree but in HeavyMesh and is fixed already)

**Comment by bpatzak** [comment]
I think that was addressed already in the past, where we supported fastOctant (see https://github.com/mupif/mupif/commit/475029404161d9ead0aaf3f46a839da45a323eeb) which led to significant improvements.
Perhaps we should reconsider the support for fastOctant.

**Comment by eudoxos** [comment]
I will look at that option; it should be adjusted to use pybind11 instead of boost::python: that is doable and will make it easier to distribute.

One more option (I am not much inclined to) would be to use python-vtk (which does have binary distributions, including windows) and use its `vtkLocator` classes as an option.

**Comment by eudoxos** [comment]
I have updated (not commited yet) the fastOctant, with pybind11. So far:

1. Lot of the time was actually spent in iterating over vertices to get global bbox of the mesh (`getVertex` constructs a `Vertex` object); this is accelerated now somewhat. Is it safe to assume that bbox of the mesh volume is not larger than envelope of the vertex points?

3. Lot of time is now (even with `fastOctant`) spent in `getBBox` on cells — one after another constructs `Vertex` objects, gets their bbox, and then they are destroyed again. Similar question: can one assume that vertex point bbox is not smaller than one single cell volume bbox, regardless of cell type? If so, there is potential for a substantial acceleration.

This is a part of `cProfile` output — most of the evaluate cumulative time is taken by all the `getBBox` calls, inside which `getVertex` are called many times. The mesh had 175k vertices and 155k tetras.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   [...]
        3    0.002    0.001  799.756  266.585 field.py:208(_evaluate)
        3    0.954    0.318  797.401  265.800 mesh.py:464(getCellLocalizer)
   154788   73.935    0.000  612.440    0.004 octree.py:260(insert)
  1146864   11.630    0.000  538.506    0.000 cell.py:143(getBBox)
   154788    2.661    0.000  506.061    0.003 cell.py:156(<listcomp>)
  1244736   51.954    0.000  505.545    0.000 heavymesh.py:61(getVertex)
```

**Comment by eudoxos** [comment]
For HeavyUnstructuredMesh, `getCellLocalizer` now takes 15s for those 155k tetras with `fastOctant`: the Octree was changed to store cell ID and its associated bounding box (1 int, 6 floats) instead of reference to the `Cell` object in python, and BoundingBoxes are computed from vertices (for certain cell types only; for other cells, the `Cell` object is requested from the mesh and `getBBox()` is called on it — this was not much tested as we have no cells types that stick out of the vertex hull).

![image](https://user-images.githubusercontent.com/1029876/172463113-406077e3-64bd-4ce5-b2fa-c83d749e52db.png)


It is required that complete vertex coordinate array is stored in memory (this could be theoretically worked around by passing HDF5 object ID into c++, and access that object ID from c++-side HDF5 library —  see e.g. https://github.com/h5py/h5py/issues/1821 for an idea), though it is a compact array and considering 8×3 bytes per coordinate, 1G RAM can take something like 44M vertices. So I am not much worried.

We depend on pybind11 and Eigen; Eigen will be unfortunately  necessary as pybind11 can pass numpy arrays without copying as Eigen's objects. This would be quite difficult to write again.

**Comment by eudoxos** [comment]
The previous was in debug mode. It is down to almost zero with optimizations.
```
octree: 160000.0 cells [00:00, 1015324.13 cells/s]
```

**Comment by eudoxos** [comment]
This is getting fixed in with https://github.com/mupif/mupif-accel .
