### ISSUE TITLE
MuPIF examples

### ISSUE THREAD

**Issue by bpatzak** [mupif/mupif#85]
Some other modules (mupif/jypyter) rely on models from mupif examples. However, the models are not imported when importing mupif into jupyter notebook or into any other other python script. 
In mupif/jupyter  this is solved by cloning the models.py, which is not nice. 
The are 2 possible solutions:
- allow to import models.py from mupif, but not by default (not sure if possible)
- make examples as independent module.

**Comment by eudoxos** [comment]
> * allow to import models.py from mupif, but not by default (not sure if possible)

This is definitely possible. We are currently importing most mupif sub-modules in `__init__.py` and putting their classes into the `mupif.*` namespace; skipping such examples is not an issue. We could add e.g. `mupif/demo` directory with those relevant files, so the models would be `mupif.demo.models.ThermalModel` but importing it automatically as `mupif.demo.ThermalModel` and similar. Is there going to be something more than just models? If not, the structure might be flatter.

**Comment by eudoxos** [comment]
Please have a look at 405d84935140b8376fec3e93be09958892e28508: `mupif.demo.*`; in the end, I did not bother with avoiding the automatic import, it won't take any significant time I think and avoids the necessity of importing the module explicitly, in addition to mupif itself.
